# Generated by Django 4.1.2 on 2022-10-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
